//Request All
GET http://localhost:5271/times

###
//Request By Id
GET http://localhost:5271/times/3

###
//POST
POST http://localhost:5271/times/
Content-Type: application/json

{
  "nome": "Paris Saint German",
  "cidade": "Paris",
  "TitulosBrasileiros": 0,
  "TitulosMundiais": 8
}


###
//PUT - UPDATE
PUT http://localhost:5271/times/3
Content-Type: application/json

{
"nome": "Curintia",
"cidade": "Sampa",
"TitulosBrasileiros": 99,
"TitulosMundiais": 999
}

###
//DELETE
DELETE http://localhost:5271/times/12
